### ISSUE TITLE
gr.in / gr.match deprecate

### ISSUE THREAD

**Issue by jwalabroad** [mskilab/gUtils#1]
gr.in wraps gr.findoverlaps to produce a faster %over% from GenomicRanges. The new %over% is significantly faster, so suggest deleting gr.in

**Comment by jwalabroad** [comment]
Same thing with gr.match.

**Comment by mskilab** [comment]
gr.in and gr.match have a "by" category, and also don't break when seqnames or genomes don't match, also a lot of downstream code uses this heavily

**Comment by mskilab** [comment]
btw there are additional features that gr.in, gr.findoverlaps, and gr.match provide which is useful in practice --> namely chunking up super big queries so that a user can modulate the memory footprint or parallelize with mc.cores.  

I noticed you removed these from gr.findoverlaps - this will already break fish.hook and a bunch of other code.  More generally, can we be a little more conservative in deleting stuff?  A lot of code depends on gUtils functions existing and having certain arguments.  We can selective un-document certain functionality that may not be more widely useful, but let's make changes backward compatible.

**Comment by jwalabroad** [comment]
The problem is that we can't just undocument code, or it won't pass R CMD check and won't be admissible to CRAN or Bioconductor. I'm also worried about the headache of maintaining a hidden parallelization inside functions, as this is much more system-specific and is liable to break on R version X on system Y. 

For this case, I agree that we can put the chunking back in, but propose doing an "lapply" only?

It's easy to put things back in, and I'll keep doing this. We just need to document explicitly why they are useful over GenomicRanges capabilities. If there are redundancies that can be avoided, it would be better to patch downstream code rather than maintain something not generally useful to a new gUtils user.

**Comment by jwalabroad** [comment]
Chunks are back in gr.findoverlaps. Also added sort before return to ensure that outputs are identical w or w/o chunking.

**Comment by jwalabroad** [comment]
gr.match and gr.in are now back.
