### ISSUE TITLE
grbind is slow

### ISSUE THREAD

**Issue by walaj** [mskilab/gUtils#13]
Just leaving a note here that grbind is very slow (its not done after 1 min on binding two < 1e6 GRanges).

**Comment by mskilab** [comment]
ouch not sure what's driving this .. grbind and its unfortunate cousin
rrbind continue to cause problems with DataFrames / data.frames /
data.tables

**Comment by walaj** [comment]
Ultimate solution would be to move entirely to data.table functions. Add a grl.ix field and you've got a grangeslist structure. Would be super light weight and independent. What is granges giving that we can't get with data table? Maybe coverage and reduce, but those are easily reimplemented. Just a thought, could take away so many headaches for years to come :)

**Comment by mskilab** [comment]
Hmm, tempting but might be more pain that it's worth

Main reason is findoverlaps is much quicker w GRanges than
data.table:foverlaps currently - foverlaps would very slow at times I recall

we would need to reimplement seqlengths concept, and a ton of basic ops ..
otherwise a lot of downstream stuff would break

however data.table rbindlist with fill = TRUE might solve a bunch of the
table concatenation problems .. though I feel like we tried that before

**Comment by walaj** [comment]
Yeah, you're probably right. Maybe over time enough data.table functionality will be built to make this easier. 

I hadn't thought to use rbindlist with fill option, i imagine it should work...
