### ISSUE TITLE
%Q% no longer used?

### ISSUE THREAD

**Issue by KhagayN** [mskilab/gUtils#6]
I reinstalled gUtils but, it seems like the %Q% subset function is no longer defined. What are we using instead?

**Comment by KhagayN** [comment]
`dfddf`

**Comment by jwalabroad** [comment]
Hmm, I don't see it in dev/gUtils either. Not sure what this did, presumably a shortcut for something

**Comment by jwalabroad** [comment]
They're all here:
https://github.com/mskilab/gUtils/blob/103b0bdc447bb4f660bd5ec7d40a6cec76e7827f/R/gUtils.R

**Comment by mskilab** [comment]
dev/gUtils is from last May - we should compare to a more recent gUtils from the main repo but say January 2016 or December 2015

!!!! I use %Q% all the time - can we add this back?

**Comment by KhagayN** [comment]
ah okay. I just tried mskilab/gUtils %Q% and it looks like it can't be found either.

**Comment by jwalabroad** [comment]
The link above points to a mid Feb version with %Q%, so it should be copied over from there to current mskilab/gUtils.R and R CMD check'ed etc.

**Comment by KhagayN** [comment]
I'll move it over

**Comment by KhagayN** [comment]
"%Q%" has been added back. Ran R CMD check and got an error that we're using we're loading BSgenome.Hsapiens.UCSC.hg19 but, we haven't installed that package yet.

**Comment by jwalabroad** [comment]
OK awesome that %Q% is back. 

R CMD check will run the examples so will fail if you don't have the package. This is 100% OK though, because it is under "Suggests" in DESCRIPTION. This is exactly what suggests is for, packages that are for running examples but not for the code itself. If you run R CMD check though (should be developors only, not users), then it will require this. 

This is OK though because with TravisCI it will install all the "Suggests" package as well when building. No need to do "install.packages" anywhere.

I committed some other fixes that make other warnings go away. Take a look at the @aliases tag for the setMethod type methods.

**Comment by KhagayN** [comment]
ahh, I see now, no wonder Travis CI build worked but R CMD check didn't. Thanks for the tip.

**Comment by KhagayN** [comment]
Which shortcuts should I put back?

**Comment by jwalabroad** [comment]
I would say put back whatever makes sense for a general user, so I am expecting most of them. Whatever you add back, just make sure to write a testthat test for it :)

**Comment by KhagayN** [comment]
%^% has been added back and a testthat for it. 

cov is a GRanges object 
`print(expect_that(length(cov %^% cov) , equals(length(cov)))) 
As expected: length(cov %^% cov) equals length(cov)`

**Comment by jwalabroad** [comment]
great, thanks! 

I can't see the above test in test_ranges, did this not make it into the latest commit? Test looks good.

**Comment by KhagayN** [comment]
Sorry about that. Tests have been added for %Q% and %^% in test_ranges.
